name: Design workflow remote commands

on:
  issues:
    types:
      - opened

permissions: {}

jobs:
  execute:
    if: github.event.issue.title == '[design-workflow] command'
    permissions:
      contents: write
      issues: write
    uses: ferfalcon/figma-to-implementation-workflow/.github/workflows/design-workflow-command.yml@8c3e92413be821e9a25980a074004f2de3414d7f
